$:
  vscode:
    - docker:
        build: .ide/Dockerfile
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: install dep
          script: pnpm i
      # 开发环境销毁前会执行该任务
      endStages:
        - name: end stage
          script: echo "end stage"

main:
  push:
    - imports: https://cnb.cool/my-codespace/envs/-/blob/main/github-secret.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/NPCDW/loemby.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_ACCESS_TOKEN}
